// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendAgreementLetter mocks base method.
func (m *MockEmailService) SendAgreementLetter(investorId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAgreementLetter", investorId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAgreementLetter indicates an expected call of SendAgreementLetter.
func (mr *MockEmailServiceMockRecorder) SendAgreementLetter(investorId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAgreementLetter", reflect.TypeOf((*MockEmailService)(nil).SendAgreementLetter), investorId)
}
